apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger
spec:
  params:
    - name: source-repo
      description: Source code repository
    - name: sha
      description: Precise SHA of the commit to build
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: flask-mysql-pipeline-run-
      spec:
        pipelineRef:
          name: flask-mysql-app-pipeline
        serviceAccountName: vcs-trigger
        params:
          - name: app-name
            value: flask-mysql-app
          - name: source-repo
            value: $(tt.params.source-repo)  # use value from trigger event
          - name: sha                        # introduce new param
            value: $(tt.params.sha)          # use value from trigger event
          - name: image-repo
            value: quay.io/hejinchi_ibm/flask-mysql-app
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
