apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: flask-mysql-app-pipeline-run-
spec:
  pipelineRef:
    name: nodejs-pipeline
  serviceAccountName: vcs-trigger
  params:
    - name: app-name
      value: flask-mysql-app
    - name: source-repo
      value: https://github.com/jinchihe/flask-mysql-app
    - name: image-repo
      value: quay.io/hejinchi_ibm/flask-mysql-app
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
