apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flaskapi-deployment.yaml
  - flaskapi-service.yaml
  - flaskapi-route.yaml
commonLabels:
  app: flaskapi
  app.kubernetes.io/instance: flaskapi-instance
  app.kubernetes.io/name: flaskapi
