apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jinchi-mysql-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
