apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 795f6518860e55150986ab608fe9283f72221e23
    app.openshift.io/vcs-uri: https://github.com/jinchihe/flask-mysql-app
  labels:
    app: jinchihe-assignment
    app.kubernetes.io/instance: jinchihe-assignment
    app.kubernetes.io/name: jinchihe-assignment-flask-mysql-app
    app.openshift.io/runtime: js
  name: flaskapi-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: jinchihe-assignment
    app.kubernetes.io/instance: jinchihe-assignment
    app.kubernetes.io/name: jinchihe-assignment-flask-mysql-app
    app.openshift.io/runtime: js
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 795f6518860e55150986ab608fe9283f72221e23
    app.openshift.io/vcs-uri: https://github.com/jinchihe/flask-mysql-app
  labels:
    app: jinchihe-assignment
    app.kubernetes.io/instance: jinchihe-assignment
    app.kubernetes.io/name: jinchihe-assignment-flask-mysql-app
    app.openshift.io/runtime: js
  name: flaskapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jinchihe-assignment
      app.kubernetes.io/instance: jinchihe-assignment
      app.kubernetes.io/name: jinchihe-assignment-flask-mysql-app
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 795f6518860e55150986ab608fe9283f72221e23
        app.openshift.io/vcs-uri: https://github.com/jinchihe/flask-mysql-app
      labels:
        app: jinchihe-assignment
        app.kubernetes.io/instance: jinchihe-assignment
        app.kubernetes.io/name: jinchihe-assignment-flask-mysql-app
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: db_root_password
          valueFrom:
            secretKeyRef:
              key: db_root_password
              name: flaskapi-secrets
        - name: db_name
          value: flaskapi
        image: quay.io/hejinchi_ibm/flask-mysql-app:795f6518860e55150986ab608fe9283f72221e23
        imagePullPolicy: IfNotPresent
        name: flaskapi
        ports:
        - containerPort: 5000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 795f6518860e55150986ab608fe9283f72221e23
    app.openshift.io/vcs-uri: https://github.com/jinchihe/flask-mysql-app
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: jinchihe-assignment
    app.kubernetes.io/instance: jinchihe-assignment
    app.kubernetes.io/name: jinchihe-assignment-flask-mysql-app
    app.openshift.io/runtime: js
  name: flaskapi-route
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: flaskapi-service
    weight: 100
  wildcardPolicy: None
